import type { Advertisement, Application, RewardItem, StudentProfile, VaultDocument } from "@/lib/types";

export const emptyProfile: StudentProfile = {
  fullName: "",
  country: "",
  school: "",
  grade: 11,
  graduationYear: new Date().getFullYear() + 1,
  age: 17,
  gradingSystem: "gpa4",
  gpa: null,
  sat: null,
  act: null,
  ib: null,
  aLevels: "",
  apCourses: "",
  ielts: null,
  toefl: null,
  duolingo: null,
  fields: [],
  interestsNote: "",
  activities: [],
  annualBudgetUsd: 20000,
  tuitionRange: [0, 40000],
  needsAid: false,
  scholarshipRequired: false,
  preferredCountries: [],
  preferredRegions: [],
  campusType: "any",
  institutionType: "any",
  size: "any",
  careerGoal: "",
  gradSchool: "undecided",
  currentStreak: 1,
  totalExp: 100,
  chosenTotem: "alikhan",
  lastActiveDate: new Date().toISOString().slice(0, 10),
  isBusinessAccount: false,
  avatarUrl: "",
};

export const sampleProfile: StudentProfile = {
  ...emptyProfile,
  fullName: "Aruzhan Sadykova",
  country: "Kazakhstan",
  school: "Nazarbayev Intellectual School, Almaty",
  grade: 12,
  graduationYear: new Date().getFullYear() + 1,
  age: 17,
  gradingSystem: "five_point",
  gpa: 4.8,
  sat: 1480,
  ielts: 7,
  fields: ["Computer Science", "Artificial Intelligence"],
  interestsNote: "Computer vision for agriculture and medical imaging",
  activities: [
    {
      id: "a1",
      category: "Olympiad",
      title: "Republican Olympiad in Informatics",
      role: "Participant",
      level: "national",
      impact: "Silver medal",
      evidence: "Certificate",
      link: "",
      hoursPerWeek: 6,
    },
    {
      id: "a2",
      category: "Project",
      title: "Crop disease detection app",
      role: "Founder and developer",
      level: "city",
      impact: "Used by 40 farmers in Almaty region; 87% accuracy on test images",
      evidence: "GitHub repository",
      link: "https://github.com",
      hoursPerWeek: 5,
    },
    {
      id: "a3",
      category: "Club",
      title: "School robotics club",
      role: "President",
      level: "school",
      impact: "Grew membership from 8 to 30 students",
      evidence: "",
      link: "",
      hoursPerWeek: 3,
    },
  ],
  annualBudgetUsd: 15000,
  tuitionRange: [0, 20000],
  needsAid: true,
  scholarshipRequired: true,
  preferredCountries: ["United States", "Canada", "South Korea"],
  preferredRegions: ["Europe"],
  campusType: "any",
  institutionType: "any",
  size: "any",
  careerGoal: "Machine learning engineer working on computer vision, possibly a PhD later",
  gradSchool: "phd",
  currentStreak: 5,
  totalExp: 750,
  chosenTotem: "alikhan",
  lastActiveDate: new Date().toISOString().slice(0, 10),
  isBusinessAccount: false,
};

export const defaultVaultDocuments: VaultDocument[] = [
  {
    id: "doc-pass-1",
    category: "passport",
    name: "International Passport (Bio-page)",
    fileName: "passport_scan_valid2028.pdf",
    fileSize: "2.4 MB",
    status: "verified",
    uploadedAt: "2026-09-01",
  },
  {
    id: "doc-inc-1",
    category: "family_income",
    name: "Employer Income Certificate (Parents)",
    fileName: "income_certificate_2025.pdf",
    fileSize: "1.1 MB",
    status: "needs_translation",
    uploadedAt: "2026-09-05",
    notes: "Requires certified apostilled English translation",
  },
  {
    id: "doc-bank-1",
    category: "bank_statement",
    name: "Bank Statement (Last 6 Months)",
    fileName: "halyk_bank_statement_6m.pdf",
    fileSize: "3.8 MB",
    status: "verified",
    uploadedAt: "2026-09-10",
  },
  {
    id: "doc-tax-1",
    category: "tax",
    name: "Annual Tax Return (Form 240 / 250)",
    status: "missing",
  },
  {
    id: "doc-ins-1",
    category: "insurance",
    name: "International Student Health Insurance Clearance",
    status: "missing",
  },
];

export const defaultRewards: RewardItem[] = [
  {
    id: "rw-1",
    title: "1-on-1 Ivy League Admissions & Career Counseling",
    category: "counseling",
    cost: 500,
    description: "60-minute strategic counseling session with a Harvard/MIT graduate admissions advisor.",
    discountCode: "MERIDIAN-IVY-1ON1",
    provider: "IvyAdvisors Network",
    badge: "Most Popular",
  },
  {
    id: "rw-2",
    title: "IELTS Band 8+ Intensive Preparation Course Voucher",
    category: "ielts",
    cost: 350,
    description: "Full access to live masterclasses, speaking simulator, and 10 full-length mock exams.",
    discountCode: "IELTS-BAND8-VIP",
    provider: "IELTS Zone Academy Almaty",
    badge: "Verified Partner",
  },
  {
    id: "rw-3",
    title: "Common App & Global University Fee Waiver Code",
    category: "waiver",
    cost: 700,
    description: "Official institutional partner application fee waiver package for up to 5 universities.",
    discountCode: "MERIDIAN-WAIVER-2026",
    provider: "Global Admissions Consortium",
    badge: "Limited Stock",
  },
  {
    id: "rw-4",
    title: "SAT 1550+ Digital Practice Sprint Pass",
    category: "sat",
    cost: 250,
    description: "Adaptive Bluebook-style question bank with AI explanation breakdown and weak-area drills.",
    discountCode: "SAT-1550-SPRINT",
    provider: "IvyPrep Kazakhstan",
    badge: "Instant Unlock",
  },
  {
    id: "rw-5",
    title: "Elite Admissions Personal Statement Dean's Review",
    category: "essay",
    cost: 600,
    description: "Comprehensive line-by-line developmental edit and positioning critique by former admissions dean.",
    discountCode: "ESSAY-DEAN-PASS",
    provider: "Meridian Senior Review Board",
    badge: "Highest Impact",
  },
];

export const defaultAdvertisements: Advertisement[] = [
  {
    id: "ad-ielts-kz",
    b2bAccountId: "b2b-ieltszone",
    title: "IELTS Zone Almaty & Astana: Band 7.5+ Intensive Course",
    subtitle: "Localized Kazakhstani group & individual prep with British Council certified instructors",
    targetCountry: "Kazakhstan",
    targetKeyword: "ielts",
    ctaLabel: "Get 25% Meridian Discount",
    ctaUrl: "https://ieltszone.kz",
    discountNote: "Promo Code: MERIDIAN25",
    impressions: 1420,
    clicks: 184,
    active: true,
  },
  {
    id: "ad-sat-kz",
    b2bAccountId: "b2b-ivyprep",
    title: "IvyPrep Kazakhstan: Digital SAT 1500+ Weekend Bootcamp",
    subtitle: "Proven results for NIS and Bilim-Innovation Lyceum students aiming for Top 20 US universities",
    targetCountry: "Kazakhstan",
    targetKeyword: "sat",
    ctaLabel: "Claim Free Diagnostic Exam",
    ctaUrl: "https://ivyprep.kz",
    discountNote: "Free Mock Test Included",
    impressions: 980,
    clicks: 112,
    active: true,
  },
  {
    id: "ad-consulting-global",
    b2bAccountId: "b2b-globalivy",
    title: "AdmitMaster: Full-Ride Scholarship Advisory",
    subtitle: "Specialized guidance for Central Asian applicants applying for need-blind and merit scholarships",
    targetCountry: "all",
    targetKeyword: "scholarship",
    ctaLabel: "Schedule Free Evaluation",
    ctaUrl: "https://admitmaster.org",
    discountNote: "Priority Review",
    impressions: 2150,
    clicks: 290,
    active: true,
  },
];

export function newApplication(universitySlug: string, scholarshipIds: string[] = []): Application {
  return {
    universitySlug,
    status: "researching",
    documents: [
      { id: "transcript", name: "Official transcript", done: false },
      { id: "recommendations", name: "Two recommendation letters", done: false },
      { id: "english", name: "English test report", done: false },
      { id: "passport", name: "Passport copy", done: false },
      { id: "financial", name: "Financial documents", done: false },
    ],
    essays: [
      { id: "personal", name: "Personal statement", done: false },
      { id: "supplemental", name: "Supplemental essays", done: false },
    ],
    scholarshipIds,
    notes: "",
    addedAt: new Date().toISOString(),
  };
}
