import type { Application, StudentProfile } from "@/lib/types";

export const emptyProfile: StudentProfile = {
  fullName: "",
  country: "",
  school: "",
  grade: 11,
  graduationYear: new Date().getFullYear() + 1,
  age: 17,
  gradingSystem: "gpa4",
  gpa: null,
  sat: null,
  act: null,
  ib: null,
  aLevels: "",
  apCourses: "",
  ielts: null,
  toefl: null,
  duolingo: null,
  fields: [],
  interestsNote: "",
  activities: [],
  annualBudgetUsd: 20000,
  tuitionRange: [0, 40000],
  needsAid: false,
  scholarshipRequired: false,
  preferredCountries: [],
  preferredRegions: [],
  campusType: "any",
  institutionType: "any",
  size: "any",
  careerGoal: "",
  gradSchool: "undecided",
};

export const sampleProfile: StudentProfile = {
  ...emptyProfile,
  fullName: "Aruzhan Sadykova",
  country: "Kazakhstan",
  school: "Nazarbayev Intellectual School, Almaty",
  grade: 12,
  graduationYear: new Date().getFullYear() + 1,
  age: 17,
  gradingSystem: "five_point",
  gpa: 4.8,
  sat: 1480,
  ielts: 7,
  fields: ["Computer Science", "Artificial Intelligence"],
  interestsNote: "Computer vision for agriculture and medical imaging",
  activities: [
    {
      id: "a1",
      category: "Olympiad",
      title: "Republican Olympiad in Informatics",
      role: "Participant",
      level: "national",
      impact: "Silver medal",
      evidence: "Certificate",
      link: "",
      hoursPerWeek: 6,
    },
    {
      id: "a2",
      category: "Project",
      title: "Crop disease detection app",
      role: "Founder and developer",
      level: "city",
      impact: "Used by 40 farmers in Almaty region; 87% accuracy on test images",
      evidence: "GitHub repository",
      link: "https://github.com",
      hoursPerWeek: 5,
    },
    {
      id: "a3",
      category: "Club",
      title: "School robotics club",
      role: "President",
      level: "school",
      impact: "Grew membership from 8 to 30 students",
      evidence: "",
      link: "",
      hoursPerWeek: 3,
    },
  ],
  annualBudgetUsd: 15000,
  tuitionRange: [0, 20000],
  needsAid: true,
  scholarshipRequired: true,
  preferredCountries: ["United States", "Canada", "South Korea"],
  preferredRegions: ["Europe"],
  campusType: "any",
  institutionType: "any",
  size: "any",
  careerGoal: "Machine learning engineer working on computer vision, possibly a PhD later",
  gradSchool: "phd",
};

export function newApplication(universitySlug: string, scholarshipIds: string[] = []): Application {
  return {
    universitySlug,
    status: "researching",
    documents: [
      { id: "transcript", name: "Official transcript", done: false },
      { id: "recommendations", name: "Two recommendation letters", done: false },
      { id: "english", name: "English test report", done: false },
      { id: "passport", name: "Passport copy", done: false },
      { id: "financial", name: "Financial documents", done: false },
    ],
    essays: [
      { id: "personal", name: "Personal statement", done: false },
      { id: "supplemental", name: "Supplemental essays", done: false },
    ],
    scholarshipIds,
    notes: "",
    addedAt: new Date().toISOString(),
  };
}
