import type { FieldOfStudy, Locale, RecommendedActivity, StudentProfile } from "@/lib/types";

const majorActivityCatalog: Record<string, Omit<RecommendedActivity, "id">[]> = {
  "Computer Science": [
    {
      title: "USACO / National Olympiad in Informatics",
      category: "Olympiad",
      field: "Computer Science",
      role: "Competitor & Problem Solver",
      description: "Train algorithmic depth in dynamic programming, graph theory, and data structures to achieve Gold/Platinum tier.",
      impactPotential: "Elite",
      level: "national",
      estimatedHoursPerWeek: 6,
      xpReward: 450,
      roadmapTaskTitle: "Complete 15 USACO Gold algorithmic training problems",
    },
    {
      title: "Major Open-Source Project Contribution",
      category: "Project",
      field: "Computer Science",
      role: "Core Contributor",
      description: "Contribute bug fixes, feature PRs, and documentation to established open-source tools on GitHub.",
      impactPotential: "High",
      level: "international",
      estimatedHoursPerWeek: 4,
      xpReward: 300,
      roadmapTaskTitle: "Get 3 pull requests merged into open-source repositories",
    },
    {
      title: "Global 48-Hour Hackathon Championship",
      category: "Competition",
      field: "Computer Science",
      role: "Full-Stack Architect",
      description: "Build an end-to-end web/cloud application solving a real community challenge under time pressure.",
      impactPotential: "Very High",
      level: "international",
      estimatedHoursPerWeek: 5,
      xpReward: 350,
      roadmapTaskTitle: "Register and submit working prototype to international hackathon",
    },
  ],
  "Artificial Intelligence": [
    {
      title: "Kaggle Grandmaster Track & Model Development",
      category: "Competition",
      field: "Artificial Intelligence",
      role: "Machine Learning Engineer",
      description: "Train computer vision or NLP transformers on benchmark datasets, publishing verifiable notebooks.",
      impactPotential: "Elite",
      level: "international",
      estimatedHoursPerWeek: 6,
      xpReward: 500,
      roadmapTaskTitle: "Publish Kaggle notebook achieving top 5% public leaderboard rank",
    },
    {
      title: "Empirical AI Research Paper Submission",
      category: "Research",
      field: "Artificial Intelligence",
      role: "Lead Student Researcher",
      description: "Conduct novel ablation studies or benchmark evaluations under faculty mentorship and publish a preprint on arXiv.",
      impactPotential: "Elite",
      level: "international",
      estimatedHoursPerWeek: 7,
      xpReward: 600,
      roadmapTaskTitle: "Complete draft of empirical AI preprint with professor review",
    },
    {
      title: "Responsible AI Community Workshop Series",
      category: "Leadership",
      field: "Artificial Intelligence",
      role: "Organizer & Speaker",
      description: "Deliver a series of accessible AI ethics and coding workshops for 100+ middle and high school students.",
      impactPotential: "High",
      level: "city",
      estimatedHoursPerWeek: 3,
      xpReward: 250,
      roadmapTaskTitle: "Conduct 3-part AI literacy seminar for youth",
    },
  ],
  "Economics": [
    {
      title: "Wharton Global High School Investment Challenge",
      category: "Competition",
      field: "Economics",
      role: "Team Portfolio Strategist",
      description: "Manage a simulated $100k portfolio, developing client-focused asset allocation and risk management strategies.",
      impactPotential: "Elite",
      level: "international",
      estimatedHoursPerWeek: 5,
      xpReward: 450,
      roadmapTaskTitle: "Submit comprehensive investment analysis report to Wharton challenge",
    },
    {
      title: "Regional Microeconomic Impact Study",
      category: "Research",
      field: "Economics",
      role: "Economic Analyst",
      description: "Analyze price elasticity and small business revenue shifts in your city utilizing public economic datasets.",
      impactPotential: "Very High",
      level: "national",
      estimatedHoursPerWeek: 4,
      xpReward: 350,
      roadmapTaskTitle: "Publish microeconomic whitepaper on local small business dynamics",
    },
  ],
  "Business": [
    {
      title: "DECA / FBLA Business Strategy Competition",
      category: "Competition",
      field: "Business",
      role: "Case Analyst",
      description: "Deliver competitive case presentations on market expansion, operations, and financial feasibility.",
      impactPotential: "Very High",
      level: "national",
      estimatedHoursPerWeek: 4,
      xpReward: 350,
      roadmapTaskTitle: "Complete state qualifying case simulation for DECA",
    },
    {
      title: "Student Venture with Monetized Traction",
      category: "Startup",
      field: "Business",
      role: "Founder & CEO",
      description: "Launch an e-commerce, service, or software business that demonstrates genuine revenue or active users.",
      impactPotential: "Elite",
      level: "city",
      estimatedHoursPerWeek: 6,
      xpReward: 500,
      roadmapTaskTitle: "Reach first $1,000 in revenue or 500 active service users",
    },
  ],
  "Medicine": [
    {
      title: "Clinical Hospital Shadowing & Patient Care",
      category: "Internship",
      field: "Medicine",
      role: "Medical Shadow / Observer",
      description: "Shadow physicians across oncology, surgery, or pediatrics to document patient care pathways.",
      impactPotential: "Very High",
      level: "city",
      estimatedHoursPerWeek: 5,
      xpReward: 400,
      roadmapTaskTitle: "Complete 40 hours of verified physician shadowing and reflective logs",
    },
    {
      title: "Public Health Community Screening Drive",
      category: "Volunteering",
      field: "Medicine",
      role: "Initiative Coordinator",
      description: "Collaborate with healthcare NGOs to organize blood pressure and preventative health screenings.",
      impactPotential: "High",
      level: "city",
      estimatedHoursPerWeek: 4,
      xpReward: 300,
      roadmapTaskTitle: "Organize preventative health checkup day serving 100+ local citizens",
    },
  ],
  "Biology": [
    {
      title: "International Biology Olympiad (IBO) Pathway",
      category: "Olympiad",
      field: "Biology",
      role: "Olympiad Scholar",
      description: "Master biochemistry, molecular biology, genetics, and plant anatomy to qualify for national finals.",
      impactPotential: "Elite",
      level: "national",
      estimatedHoursPerWeek: 6,
      xpReward: 450,
      roadmapTaskTitle: "Complete Campbell Biology intensive review and past qualifying exam series",
    },
  ],
};

const defaultActivities: Omit<RecommendedActivity, "id">[] = [
  {
    title: "National Scholastic Essay & Research Prize",
    category: "Competition",
    field: "Economics",
    role: "Essayist & Scholar",
    description: "Submit a rigorous analytical paper addressing global sustainable development to top essay competitions.",
    impactPotential: "Very High",
    level: "national",
    estimatedHoursPerWeek: 4,
    xpReward: 350,
    roadmapTaskTitle: "Draft and submit 2,000-word competitive essay",
  },
  {
    title: "Community Non-Profit Digital Initiative",
    category: "Leadership",
    field: "Computer Science",
    role: "Project Director",
    description: "Lead a team to modernize website and communication infrastructure for a registered local non-profit.",
    impactPotential: "High",
    level: "city",
    estimatedHoursPerWeek: 3,
    xpReward: 250,
    roadmapTaskTitle: "Deploy modernized portal for local charity organization",
  },
];

export function getRecommendationsForProfile(
  profile: StudentProfile,
  locale: Locale = "en"
): RecommendedActivity[] {
  const chosenField = profile.fields[0] || "Computer Science";
  const templates = majorActivityCatalog[chosenField] || majorActivityCatalog["Computer Science"] || defaultActivities;

  const existingCategories = new Set(profile.activities.map((a) => a.category));

  return templates.map((tmpl, idx) => ({
    ...tmpl,
    id: `rec-${chosenField.toLowerCase().replace(/\s+/g, "-")}-${idx}`,
    impactPotential: !existingCategories.has(tmpl.category) ? "Elite" : tmpl.impactPotential,
  }));
}
